blog/urls.py
from django.urls import path
from . import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('new', blog_views.NewBlogView.as_view(), name="new_blog"),
    path('<int:blog_id>/', blog_views.BlogPost.as_view(), name="blog_item"),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core_pages import views
from blog import urls as blog_urls

urlpatterns = [
    path('', views.home_page, name="home"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('blog/', include(blog_urls, namespace="blog")),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    text = models.TextField(default="")
    blog = models.ForeignKey("Blog", on_delete=models.CASCADE, default=None)

    class Meta:
        ordering = ('id', )
        unique_together = ('blog', 'text')

    def __str__(self):
        return self.text


class Blog(models.Model):

    def get_absolute_url(self):
        return reverse('blog:blog_item', args=[self.id])

core_pages/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from blog.models import Post
from django.core.exceptions import ValidationError

EMPTY_POST_ERROR = "You can't have an empty blog post"
DUPLICATE_POST_ERROR = "You've already got this in your blog"


class PostForm(forms.models.ModelForm):

    class Meta:
        model = Post
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter some text ya dummy',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': "You can't have an empty blog post"}
        }

    def save(self, for_blog):
        self.instance.blog = for_blog
        return super().save()


class ExistingBlogPostForm(PostForm):
    def __init__(self, for_blog, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.blog = for_blog

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_POST_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

blog/views.py
from .models import Post, Blog
from .forms import PostForm, ExistingBlogPostForm
from django.shortcuts import render, redirect
from django.views.generic import ListView, View


class NewBlogView(View):
    def get(self, request):
        return render(request, "blog.html", {"form": PostForm()})

    def post(self, request, *args, **kwargs):
        form = PostForm(data=request.POST)
        if form.is_valid():
            blog = Blog.objects.create()
            form.save(for_blog=blog)
            return redirect(blog)
        else:
            return render(request, 'blog.html', {'form': form})


class BlogPost(ListView):
    model = Post
    template_name = "post_list.html"
    context_object_name = "posts"

    def get(self, request, blog_id):
        blog = Blog.objects.get(id=blog_id)
        form = ExistingBlogPostForm(for_blog=blog)
        return render(request, self.template_name, {"blog": blog, "form": form})

    def post(self, request, blog_id, *args, **kwargs):
        blog = Blog.objects.get(id=blog_id)
        form = ExistingBlogPostForm(for_blog=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(blog)
        return render(request, self.template_name, {'blog': blog, "form": form})

core_pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import FormView

# Create your views here.

def home_page(request):
    return render(request, "home.html")


class RegisterView(FormView):
    form_class = UserCreationForm
    template_name = "registration/signup.html"

    def post(self, request, *args, **kwargs):
        return render(request, "registration/incredulous_response.html", {
            "user_email": request.POST["email"],
            "password": request.POST["password1"]
        })

blog/templates/blog.html
{% extends "blog_base.html" %}
{% block header_text %}Start a blog{% endblock %}
{% block form_action %}{% url 'blog:new_blog' %}{% endblock %}

blog/templates/blog_base.html
{% extends "base.html" %}
{% block title %} The Blog {% endblock title %}
{% block content %}
    <div class="container">
	<div class="row">
	    <div class="col-md-12 jumbotron">
		<div class="text-center">
		    <h1>{% block header_text %}{% endblock header_text %}</h1>
		    <form method="POST" action="{% block form_action %}{% endblock form_action %}">
			{{ form.text }}
			{% csrf_token %}
			{% if form.errors %}
			    <div class="form-group has-error">
				<span class="help-block">{{ form.text.errors }}</span>
			    </div>
			{% endif %}
		    </form>
		</div>
	    </div>
	</div>
	<div class="row">
	    <div class="col-md-6 col-md-offset-3">
		{% block table %}
		{% endblock table %}
	    </div>
	</div>
    </div>
{% endblock content %}
{% block scripts %}
    <script src="/static/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="/static/blog.js"></script>
    <script type="text/javascript">
     $(document).ready(function () {
	 window.topBlog.initialise();
     });
    </script>
{% endblock scripts %}

blog/templates/post_list.html
{% extends "blog_base.html" %}
{% block header_text %}Blog posts{% endblock %}
{% block form_action %}{% url 'blog:blog_item' blog.id %}{% endblock %}
{% block table %}
    <ul id="blog_posts" class="table">
	{% for blog_post in blog.post_set.all %}
	    <li id="blog_post_{{ blog_post.id }}">
		{{ blog_post.text }}
	    </li>
	{% endfor %}
    </ul>
{% endblock %}

core_pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Charlie Brodie: {% block title %}{% endblock title %}</title>
	<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/base.css" rel="stylesheet">
    </head>
    <body>
	{% block content %}{% endblock content %}
    </body>
    {% block scripts %}{% endblock scripts %}
</html>

core_pages/templates/home.html
{% extends 'base.html' %}

{% block title %}The Website{% endblock %}

{% block content %}
    <h1>
	Charlie Brodie: The Website
    </h1> 

    <a id="blog" href="{% url "blog:new_blog" %}">
	Blog	
    </a>
    <a id="login" href="{% url "login" %}">
	Login
    </a>
    <a id="register" href="{% url "register" %}">
	Register	
    </a>
{% endblock %}